import { useMemo,useState } from 'react'
import { Save,Printer,FileSpreadsheet } from 'lucide-react'
import * as XLSX from 'xlsx'
import { Card } from '../components/Common'
import { printAttendance } from '../utils/exporters'
export default function Attendance({data,setData}){
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [draft,setDraft]=useState({})
 const existing=id=>(data.attendance||[]).find(a=>a.date===date&&a.studentId===id)
 const get=(id,k)=>draft[id]?.[k]??existing(id)?.[k]??(k==='status'?'Hadir':'')
 const save=()=>{setData(d=>{const keep=(d.attendance||[]).filter(a=>a.date!==date);const added=d.students.map(s=>({id:existing(s.id)?.id||crypto.randomUUID(),date,studentId:s.id,status:get(s.id,'status'),note:get(s.id,'note')}));return {...d,attendance:[...keep,...added]}});alert('Absensi tersimpan.')}
 const summary=useMemo(()=>data.students.map(s=>{const list=(data.attendance||[]).filter(a=>a.studentId===s.id);return {s,H:list.filter(a=>a.status==='Hadir').length,S:list.filter(a=>a.status==='Sakit').length,I:list.filter(a=>a.status==='Izin').length,A:list.filter(a=>a.status==='Alpa').length,T:list.filter(a=>a.status==='Terlambat').length}}),[data.attendance,data.students])
 const exportExcel=()=>{const ws=XLSX.utils.aoa_to_sheet([['No','NIS','Nama','Hadir','Sakit','Izin','Alpa','Terlambat'],...summary.map((x,i)=>[i+1,x.s.nis,x.s.name,x.H,x.S,x.I,x.A,x.T])]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Rekap Absensi');XLSX.writeFile(wb,'Rekap-Absensi-Kelas-5B.xlsx')}
 return <><div className="page-head"><div><h1>Absensi Siswa</h1><p>Absensi harian dan rekap kehadiran tahun pelajaran {data.settings.year}.</p></div><div className="grade-actions"><button onClick={exportExcel}><FileSpreadsheet/>Excel</button><button onClick={()=>printAttendance(data)}><Printer/>Cetak/PDF</button></div></div><Card><div className="toolbar"><label className="inline-date">Tanggal <input type="date" value={date} onChange={e=>{setDate(e.target.value);setDraft({})}}/></label><span>{data.students.length} siswa</span></div><div className="table-wrap"><table><thead><tr><th>No</th><th>NIS</th><th>Nama Siswa</th><th>Status</th><th>Keterangan</th></tr></thead><tbody>{data.students.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{s.nis}</td><td><b>{s.name}</b><small>{s.nisn}</small></td><td><select className={`status-select ${get(s.id,'status').toLowerCase()}`} value={get(s.id,'status')} onChange={e=>setDraft({...draft,[s.id]:{...draft[s.id],status:e.target.value}})}><option>Hadir</option><option>Sakit</option><option>Izin</option><option>Alpa</option><option>Terlambat</option></select></td><td><input className="table-input" value={get(s.id,'note')} onChange={e=>setDraft({...draft,[s.id]:{...draft[s.id],note:e.target.value}})} placeholder="Keterangan opsional"/></td></tr>)}</tbody></table></div><button className="primary save" onClick={save}><Save/>Simpan Absensi</button></Card><Card className="attendance-summary"><h3>Rekap Absensi</h3><div className="table-wrap"><table><thead><tr><th>No</th><th>Nama</th><th>Hadir</th><th>Sakit</th><th>Izin</th><th>Alpa</th><th>Terlambat</th></tr></thead><tbody>{summary.map((x,i)=><tr key={x.s.id}><td>{i+1}</td><td>{x.s.name}</td><td>{x.H}</td><td>{x.S}</td><td>{x.I}</td><td>{x.A}</td><td>{x.T}</td></tr>)}</tbody></table></div></Card></>
}
