import { useMemo,useRef,useState } from 'react'
import * as XLSX from 'xlsx'
import { BookOpenCheck, CheckCircle2, Download, FileInput, FileSpreadsheet, Plus, Save, Trash2, Upload, BarChart3 } from 'lucide-react'
import { Card,Select } from '../components/Common'
import { subjects } from '../data'

const uid=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`
const clamp=v=>Math.max(0,Math.min(100,Number(v)||0))
const descFor=(tp,score)=>{
 const text=tp?.text||'tujuan pembelajaran yang ditetapkan'
 if(score>=90)return `Mencapai kompetensi dengan sangat baik dalam hal ${text}.`
 if(score>=80)return `Mencapai kompetensi dengan baik dalam hal ${text}.`
 if(score>=70)return `Cukup mampu memahami ${text}, namun masih perlu penguatan.`
 return `Perlu bimbingan dan peningkatan dalam memahami ${text}.`
}
const notify=(d,title,message,page)=>({...d,notifications:[{id:uid(),title,message,page,createdAt:new Date().toISOString(),read:false},...(d.notifications||[])]})

function Filters({data,subject,setSubject,semester,setSemester}){
 return <div className="erapor-filters"><Select label="Kelas" value={data.settings.className||'V'} disabled><option>{data.settings.className||'V'}</option></Select><Select label="Semester" value={semester} onChange={e=>setSemester(e.target.value)}><option value="1">Semester 1</option><option value="2">Semester 2</option></Select><Select label="Mata Pelajaran" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(x=><option key={x}>{x}</option>)}</Select></div>
}

export function LearningObjectives({data,setData}){
 const [subject,setSubject]=useState(subjects[0]),[semester,setSemester]=useState(data.settings.semester||'1'),[editing,setEditing]=useState(null),[text,setText]=useState('')
 const list=(data.learningObjectives||[]).filter(x=>x.subject===subject&&String(x.semester)===String(semester))
 const save=()=>{if(!text.trim())return alert('Tujuan pembelajaran belum diisi.');setData(d=>{const old=d.learningObjectives||[];const next=editing?old.map(x=>x.id===editing?{...x,text:text.trim()}:x):[...old,{id:uid(),subject,semester,text:text.trim(),active:true}];return notify({...d,learningObjectives:next},editing?'Tujuan pembelajaran diperbarui':'Tujuan pembelajaran ditambahkan',`${subject} Semester ${semester}`,'learningObjectives')});setText('');setEditing(null)}
 const remove=id=>confirm('Hapus tujuan pembelajaran ini?')&&setData(d=>({...d,learningObjectives:(d.learningObjectives||[]).filter(x=>x.id!==id)}))
 return <><div className="page-head"><div><h1>Tujuan Pembelajaran</h1><p>Kelola TP setiap mata pelajaran sebagai dasar nilai dan deskripsi rapor.</p></div></div><Card><Filters data={data} subject={subject} setSubject={setSubject} semester={semester} setSemester={setSemester}/><div className="tp-editor"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Tuliskan tujuan pembelajaran..."/><button className="primary" onClick={save}><Plus size={18}/>{editing?'Simpan Perubahan':'Tambah TP'}</button>{editing&&<button onClick={()=>{setEditing(null);setText('')}}>Batal</button>}</div><div className="table-scroll"><table className="data-table"><thead><tr><th>No</th><th>Tingkat</th><th>Fase</th><th>Semester</th><th>Tujuan Pembelajaran</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{list.length?list.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{data.settings.className||'V'}</td><td>C</td><td>{x.semester}</td><td>{x.text}</td><td><span className="status-ok">Aktif</span></td><td className="row-actions"><button onClick={()=>{setEditing(x.id);setText(x.text)}}>Edit</button><button className="danger" onClick={()=>remove(x.id)}><Trash2 size={15}/></button></td></tr>):<tr><td colSpan="7" className="empty-cell">Belum ada TP untuk pilihan ini.</td></tr>}</tbody></table></div></Card></>
}

export function ReportInput({data,setData}){
 const [tab,setTab]=useState('input'),[subject,setSubject]=useState(subjects[0]),[semester,setSemester]=useState(data.settings.semester||'1'),[draft,setDraft]=useState({}),[importRows,setImportRows]=useState([]),[importErrors,setImportErrors]=useState([])
 const fileRef=useRef(null)
 const tps=(data.learningObjectives||[]).filter(x=>x.subject===subject&&String(x.semester)===String(semester))
 const current=useMemo(()=>Object.fromEntries((data.reportGrades||[]).filter(x=>x.subject===subject&&String(x.semester)===String(semester)).map(x=>[x.studentId,x])),[data.reportGrades,subject,semester])
 const val=(sid,k)=>draft[sid]?.[k]??current[sid]?.[k]??(k==='score'?'':[])
 const update=(sid,k,v)=>setDraft(d=>({...d,[sid]:{...(d[sid]||{}),[k]:v}}))
 const toggle=(sid,k,id)=>{const a=val(sid,k)||[];update(sid,k,a.includes(id)?a.filter(x=>x!==id):[...a,id])}
 const save=()=>setData(d=>{const old=d.reportGrades||[];const touched=Object.keys(draft);const keep=old.filter(x=>!(x.subject===subject&&String(x.semester)===String(semester)&&touched.includes(x.studentId)));const add=touched.map(studentId=>{const base=current[studentId]||{};const x={...base,...draft[studentId]};const score=clamp(x.score);const optimal=x.optimal||[];const improvement=x.improvement||[];const chosen=(d.learningObjectives||[]).find(t=>t.id===(optimal[0]||improvement[0]));return{id:base.id||uid(),studentId,subject,semester,score,optimal,improvement,description:descFor(chosen,score),updatedAt:new Date().toISOString()}});return notify({...d,reportGrades:[...keep,...add]},'Nilai rapor tersimpan',`${add.length} nilai ${subject} Semester ${semester} disimpan.`,'savedGrades')})
 const downloadTemplate=()=>{const aoa=[['FORMAT IMPORT NILAI RAPOR',subject,`Kelas ${data.settings.className}`,`Semester ${semester}`],[],['NO','NISN','NIS','NAMA SISWA','NILAI RAPOR'],...data.students.map((s,i)=>[i+1,s.nisn||'',s.nis||'',s.name,''])];const ws=XLSX.utils.aoa_to_sheet(aoa);ws['!cols']=[{wch:6},{wch:16},{wch:16},{wch:32},{wch:15}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Nilai Rapor');XLSX.writeFile(wb,`Format-Nilai-${subject}-S${semester}.xlsx`)}
 const readFile=async e=>{const file=e.target.files?.[0];if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});let h=rows.findIndex(r=>r.some(v=>String(v).toUpperCase().includes('NISN'))&&r.some(v=>String(v).toUpperCase().includes('NILAI RAPOR')));if(h<0)h=rows.findIndex(r=>r.some(v=>String(v).toUpperCase()==='NISN'));if(h<0)throw new Error('Header NISN/NILAI RAPOR tidak ditemukan.');const head=rows[h].map(v=>String(v).trim().toUpperCase());const ixN=head.findIndex(v=>v==='NISN'),ixName=head.findIndex(v=>v.includes('NAMA')),ixScore=head.findIndex(v=>v.includes('NILAI RAPOR'));const parsed=[],errors=[];rows.slice(h+1).forEach((r,i)=>{const nisn=String(r[ixN]??'').trim(),name=String(r[ixName]??'').trim(),raw=r[ixScore];if(!nisn&&!name)return;const student=data.students.find(s=>String(s.nisn)===nisn)||data.students.find(s=>s.name.toLowerCase()===name.toLowerCase());if(!student)return errors.push(`Baris ${h+i+2}: siswa ${name||nisn} tidak ditemukan.`);if(raw===''||isNaN(Number(raw))||Number(raw)<0||Number(raw)>100)return errors.push(`Baris ${h+i+2}: nilai tidak valid.`);parsed.push({studentId:student.id,name:student.name,nisn:student.nisn,score:clamp(raw)})});setImportRows(parsed);setImportErrors(errors)}catch(err){setImportRows([]);setImportErrors([err.message||'File tidak dapat dibaca.'])}}
 const commitImport=()=>{if(!importRows.length)return;setData(d=>{const ids=importRows.map(x=>x.studentId),keep=(d.reportGrades||[]).filter(x=>!(x.subject===subject&&String(x.semester)===String(semester)&&ids.includes(x.studentId)));const firstTp=(d.learningObjectives||[]).find(t=>t.subject===subject&&String(t.semester)===String(semester));const add=importRows.map(x=>({id:uid(),studentId:x.studentId,subject,semester,score:x.score,optimal:firstTp?[firstTp.id]:[],improvement:[],description:descFor(firstTp,x.score),updatedAt:new Date().toISOString()}));return notify({...d,reportGrades:[...keep,...add]},'Import nilai berhasil',`${add.length} nilai berhasil diimpor.`,'savedGrades')});setImportRows([]);alert('Nilai berhasil diimpor.')}
 return <><div className="page-head"><div><h1>Input Nilai Rapor</h1><p>Input manual atau impor nilai menggunakan file Excel.</p></div></div><div className="subtabs"><button className={tab==='input'?'active':''} onClick={()=>setTab('input')}><BookOpenCheck/>Input Rapor</button><button className={tab==='import'?'active':''} onClick={()=>setTab('import')}><FileInput/>Impor Nilai Rapor</button></div><Card><Filters data={data} subject={subject} setSubject={setSubject} semester={semester} setSemester={setSemester}/>{tab==='input'?<><div className="section-actions"><button className="primary" onClick={save}><Save/>Simpan Nilai</button></div><div className="table-scroll"><table className="data-table report-input-table"><thead><tr><th>No</th><th>Nama Siswa</th><th>NISN / NIS</th><th>Nilai</th><th>TP tercapai optimal</th><th>TP perlu peningkatan</th></tr></thead><tbody>{data.students.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{s.name}</td><td>{s.nisn}<br/><small>{s.nis}</small></td><td><input className="score-input" type="number" min="0" max="100" value={val(s.id,'score')} onChange={e=>update(s.id,'score',e.target.value)}/></td><td>{tps.length?tps.map(tp=><label className="tp-check" key={tp.id}><input type="checkbox" checked={(val(s.id,'optimal')||[]).includes(tp.id)} onChange={()=>toggle(s.id,'optimal',tp.id)}/>{tp.text}</label>):<small>Tambahkan TP terlebih dahulu.</small>}</td><td>{tps.map(tp=><label className="tp-check" key={tp.id}><input type="checkbox" checked={(val(s.id,'improvement')||[]).includes(tp.id)} onChange={()=>toggle(s.id,'improvement',tp.id)}/>{tp.text}</label>)}</td></tr>)}</tbody></table></div></>:<div className="import-box"><div className="section-actions"><button onClick={downloadTemplate}><Download/>Download Format Kelas Ini</button><input ref={fileRef} type="file" accept=".xlsx,.xls" hidden onChange={readFile}/><button className="primary" onClick={()=>fileRef.current?.click()}><Upload/>Pilih File Nilai</button></div><p>Format yang dilampirkan Bapak dan format sederhana dari aplikasi sama-sama dapat dibaca. Rumus tidak dipakai sebagai nilai; hasil sel harus berupa angka 0–100.</p>{importErrors.length>0&&<div className="import-errors"><b>Perlu diperiksa:</b>{importErrors.map((x,i)=><div key={i}>• {x}</div>)}</div>}{importRows.length>0&&<><div className="table-scroll"><table className="data-table"><thead><tr><th>No</th><th>NISN</th><th>Nama</th><th>Nilai</th></tr></thead><tbody>{importRows.map((x,i)=><tr key={x.studentId}><td>{i+1}</td><td>{x.nisn}</td><td>{x.name}</td><td>{x.score}</td></tr>)}</tbody></table></div><button className="primary" onClick={commitImport}><FileSpreadsheet/>Impor {importRows.length} Nilai</button></>}</div>}</Card></>
}

export function SavedGrades({data,setData}){
 const [tab,setTab]=useState('grades'),[subject,setSubject]=useState(subjects[0]),[semester,setSemester]=useState(data.settings.semester||'1')
 const rows=data.students.map(s=>({s,g:(data.reportGrades||[]).find(x=>x.studentId===s.id&&x.subject===subject&&String(x.semester)===String(semester))})).filter(x=>x.g)
 const remove=id=>confirm('Hapus nilai ini?')&&setData(d=>({...d,reportGrades:(d.reportGrades||[]).filter(x=>x.id!==id)}))
 const removeAll=()=>confirm('Hapus semua nilai pada pilihan ini?')&&setData(d=>({...d,reportGrades:(d.reportGrades||[]).filter(x=>!(x.subject===subject&&String(x.semester)===String(semester)))}))
 return <><div className="page-head"><div><h1>Nilai Tersimpan</h1><p>Cek nilai rapor dan deskripsi ketercapaian pembelajaran.</p></div></div><div className="subtabs"><button className={tab==='grades'?'active':''} onClick={()=>setTab('grades')}>Cek Nilai Rapor</button><button className={tab==='description'?'active':''} onClick={()=>setTab('description')}>Deskripsi Nilai Rapor</button></div><Card><Filters data={data} subject={subject} setSubject={setSubject} semester={semester} setSemester={setSemester}/><div className="section-actions right"><button className="danger" disabled={!rows.length} onClick={removeAll}><Trash2/>Hapus Semua</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>No</th><th>Nama Siswa</th><th>NISN</th><th>NIS</th><th>{tab==='grades'?'Nilai Rapor':'Deskripsi Ketercapaian Pembelajaran'}</th><th>Aksi</th></tr></thead><tbody>{rows.length?rows.map(({s,g},i)=><tr key={g.id}><td>{i+1}</td><td>{s.name}</td><td>{s.nisn}</td><td>{s.nis}</td><td>{tab==='grades'?g.score:g.description}</td><td><button className="danger" onClick={()=>remove(g.id)}><Trash2 size={15}/>Hapus</button></td></tr>):<tr><td colSpan="6" className="empty-cell">Belum ada nilai tersimpan.</td></tr>}</tbody></table></div></Card></>
}

export function AssessmentCheck({data}){
 const [tab,setTab]=useState('status'),[subject,setSubject]=useState(subjects[0]),[semester,setSemester]=useState(data.settings.semester||'1'),[studentId,setStudentId]=useState(data.students[0]?.id||'')
 const all=data.reportGrades||[]
 const selected=data.students.find(s=>s.id===studentId)
 const history=all.filter(x=>x.studentId===studentId&&x.subject===subject).sort((a,b)=>String(a.semester).localeCompare(String(b.semester)))
 return <><div className="page-head"><div><h1>Cek Penilaian</h1><p>Status, capaian, dan grafik nilai rapor siswa.</p></div></div><div className="subtabs"><button className={tab==='status'?'active':''} onClick={()=>setTab('status')}>Status Penilaian</button><button className={tab==='achievement'?'active':''} onClick={()=>setTab('achievement')}>Capaian Nilai Rapor</button><button className={tab==='chart'?'active':''} onClick={()=>setTab('chart')}><BarChart3/>Grafik Nilai Rapor</button></div><Card>{tab==='status'?<div className="table-scroll"><table className="data-table"><thead><tr><th>No</th><th>Nama Mata Pelajaran</th><th>Rombel</th><th>Nilai Rapor</th><th>Deskripsi</th></tr></thead><tbody>{subjects.map((sub,i)=>{const gs=all.filter(x=>x.subject===sub&&String(x.semester)===String(semester));return <tr key={sub}><td>{i+1}</td><td>{sub}</td><td>Kelas {data.settings.className}</td><td><span className={gs.length===data.students.length?'status-ok':'status-warn'}>{gs.length} Data</span></td><td><span className={gs.filter(x=>x.description).length===data.students.length?'status-ok':'status-warn'}>{gs.filter(x=>x.description).length} Data</span></td></tr>})}</tbody></table></div>:<><Filters data={data} subject={subject} setSubject={setSubject} semester={semester} setSemester={setSemester}/><Select label="Pilih Siswa" value={studentId} onChange={e=>setStudentId(e.target.value)}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select>{tab==='achievement'?<div className="achievement-card"><h3>{selected?.name}</h3><div className="kpi-grid"><div><small>Nilai Semester {semester}</small><b>{all.find(x=>x.studentId===studentId&&x.subject===subject&&String(x.semester)===String(semester))?.score??'-'}</b></div><div><small>Jumlah TP</small><b>{(data.learningObjectives||[]).filter(x=>x.subject===subject&&String(x.semester)===String(semester)).length}</b></div></div><p>{all.find(x=>x.studentId===studentId&&x.subject===subject&&String(x.semester)===String(semester))?.description||'Belum ada deskripsi nilai.'}</p></div>:<div className="grade-chart"><h3>Perkembangan Nilai — {selected?.name}</h3>{history.length?history.map(x=><div className="chart-row" key={x.id}><span>Semester {x.semester}</span><div><i style={{width:`${x.score}%`}}/></div><b>{x.score}</b></div>):<div className="empty-cell">Belum ada data nilai untuk digrafikkan.</div>}</div>}</>}</Card></>
}
