import { useState } from 'react'
import { Plus,Trash2,X } from 'lucide-react'
import { Card,Field,Select,ExportBar } from '../components/Common'
export default function Grades({data,setData}){
 const [open,setOpen]=useState(false),[form,setForm]=useState({studentId:data.students[0]?.id||'',subject:'Matematika',type:'UH',score:0,semester:'Ganjil',note:''})
 const add=e=>{e.preventDefault();setData(d=>({...d,grades:[...d.grades,{...form,id:crypto.randomUUID(),score:Number(form.score)}]}));setOpen(false)}
 const rows=data.grades.map(g=>[data.students.find(s=>s.id===g.studentId)?.name,g.subject,g.type,g.score,g.semester,g.note])
 return <><div className="page-head"><div><h1>Penilaian</h1><p>Kelola nilai kehadiran, sikap, UH, praktik, PAS, PAT, dan PSAT.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus/>Tambah Nilai</button></div><Card><div className="toolbar"><span><b>{data.grades.length}</b> data penilaian</span><ExportBar title="Rekap Nilai Kelas 5B" columns={['Nama','Mapel','Jenis','Nilai','Semester','Catatan']} rows={rows}/></div><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Mata Pelajaran</th><th>Jenis</th><th>Nilai</th><th>Semester</th><th>Catatan</th><th></th></tr></thead><tbody>{data.grades.map(g=><tr key={g.id}><td>{data.students.find(s=>s.id===g.studentId)?.name}</td><td>{g.subject}</td><td><span className="badge neutral">{g.type}</span></td><td><b className={g.score<75?'low':''}>{g.score}</b></td><td>{g.semester}</td><td>{g.note}</td><td><button className="trash" onClick={()=>setData(d=>({...d,grades:d.grades.filter(x=>x.id!==g.id)}))}><Trash2/></button></td></tr>)}</tbody></table></div></Card>{open&&<div className="modal"><form className="modal-card compact" onSubmit={add}><div className="modal-head"><h2>Tambah Nilai</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><Select label="Siswa" value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Field label="Mata Pelajaran" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><div className="form-grid"><Select label="Jenis" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['Kehadiran','Sikap','UH','Praktik','PAS','PAT','PSAT'].map(x=><option key={x}>{x}</option>)}</Select><Field label="Nilai" type="number" min="0" max="100" value={form.score} onChange={e=>setForm({...form,score:e.target.value})}/><Select label="Semester" value={form.semester} onChange={e=>setForm({...form,semester:e.target.value})}><option>Ganjil</option><option>Genap</option></Select><Field label="Catatan" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><button className="primary wide">Simpan Nilai</button></form></div>}</>
}
