import {useMemo,useRef,useState} from 'react'
import {Camera,FileUp,ImagePlus} from 'lucide-react'
import {Card} from '../components/Common'
import {fileToOptimizedDataUrl} from '../utils/images'

const labels={schedule:'Jadwal & Tugas',exam:'Nilai & Hasil Ujian',school:'Informasi Sekolah',note:'Catatan Guru',chat:'Pesan Langsung',gallery:'Galeri Kegiatan'}
const readFile=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('File gagal dibaca'));r.readAsDataURL(file)})

export default function ParentPortal({data,setData,studentId}){
 const [selected,setSelected]=useState(studentId||data.students[0]?.id),[photoError,setPhotoError]=useState(''),[savingPhoto,setSavingPhoto]=useState(false),[docError,setDocError]=useState('')
 const fileInput=useRef(null)
 const s=data.students.find(x=>x.id===selected)
 const grades=(data.grades||[]).filter(g=>g.studentId===selected),att=(data.attendance||[]).filter(a=>a.studentId===selected)
 const avg=grades.length?Math.round(grades.reduce((a,b)=>a+Number(b.score||0),0)/grades.length):0
 const counts=['Hadir','Sakit','Izin','Alpa','Terlambat'].map(x=>[x,att.filter(a=>a.status===x).length])
 const latest=useMemo(()=>grades.slice(-12),[grades])
 const info=useMemo(()=>[...(data.familyInformation||[])].filter(x=>x.studentId==='all'||x.studentId===selected).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),[data.familyInformation,selected])
 const docs=data.familyDocuments?.[selected]||{}
 const changePhoto=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!s)return;try{setPhotoError('');setSavingPhoto(true);const photo=await fileToOptimizedDataUrl(file);setData(d=>({...d,students:d.students.map(item=>item.id===s.id?{...item,photo}:item)}))}catch(err){setPhotoError(err.message||'Foto gagal diproses.')}finally{setSavingPhoto(false)}}
 const uploadDoc=async(type,file)=>{if(!file||!s)return;try{setDocError('');if(file.size>4*1024*1024)throw new Error('Dokumen maksimal 4 MB.');const content=await readFile(file);setData(d=>({...d,familyDocuments:{...(d.familyDocuments||{}),[s.id]:{...(d.familyDocuments?.[s.id]||{}),[type]:{name:file.name,type:file.type,content,uploadedAt:new Date().toISOString()}}}}))}catch(err){setDocError(err.message)}}
 return <><div className="page-head"><div><h1>Portal Orang Tua</h1><p>Pantau informasi anak secara real-time. Data sekolah hanya dapat dilihat.</p></div>{!studentId&&<select value={selected} onChange={e=>setSelected(e.target.value)}>{data.students.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}</div>{s&&<><Card className="student-profile"><div className="parent-photo-block"><div className="avatar parent-avatar">{s.photo?<img src={s.photo} alt={`Foto ${s.name}`}/>:<span>{s.name?.[0]||<Camera/>}</span>}</div><button className="secondary photo-button parent-photo-button" type="button" disabled={savingPhoto} onClick={()=>fileInput.current?.click()}><ImagePlus/>{savingPhoto?'Memproses...':'Ganti Foto'}</button><input ref={fileInput} className="hidden-file-input" type="file" accept="image/*" onChange={changePhoto}/>{photoError&&<small className="photo-error">{photoError}</small>}</div><div><h2>{s.name}</h2><p>NISN {s.nisn} · Kelas {data.settings.className}</p><small>Orang tua: {s.parent}</small><p className="photo-sync-note">Foto yang diganti otomatis tampil pada halaman wali kelas.</p></div><div className="score-ring"><b>{avg}</b><span>Rata-rata</span></div></Card>
 <div className="grid2"><Card><h3>Absensi Harian Real-time</h3><div className="attendance-bars">{counts.map(([x,n])=><div key={x}><span>{x}</span><div><i style={{width:`${Math.min(100,n*10)}%`}}/></div><b>{n}</b></div>)}</div>{att.length>0&&<p className="parent-latest-attendance">Terakhir: <b>{att.at(-1)?.status}</b> — {att.at(-1)?.date}</p>}</Card><Card><h3>Perkembangan Nilai</h3><div className="grade-chart">{latest.map(g=><div key={g.id} title={`${g.subject} ${g.field}: ${g.score}`}><i style={{height:`${g.score}%`}}/><small>{g.field?.toUpperCase()}</small></div>)}</div></Card></div>
 <Card><h3>Dokumen Keluarga</h3><p className="muted">Orang tua diperbolehkan mengunggah Kartu Keluarga dan Akta Kelahiran.</p><div className="document-upload-grid">{[['kk','Kartu Keluarga'],['akta','Akta Kelahiran']].map(([key,label])=><label key={key} className="document-upload"><FileUp/><b>{label}</b><small>{docs[key]?.name||'Belum diunggah'}</small><input type="file" accept="image/*,.pdf" onChange={e=>uploadDoc(key,e.target.files?.[0])}/></label>)}</div>{docError&&<p className="form-error">{docError}</p>}</Card>
 <Card><h3>Informasi dari Wali Kelas</h3><div className="parent-info-list">{info.length?info.map(item=><article key={item.id} className="parent-info-item"><div><span>{labels[item.type]||'Informasi'}</span><small>{item.date}</small></div><h4>{item.title}</h4>{item.body&&<p>{item.body}</p>}{item.media&&(item.mediaType?.startsWith('video')?<video controls src={item.media}/>:<img src={item.media} alt={item.title||'Kegiatan kelas'}/>)}</article>):<p>Belum ada informasi terbaru.</p>}</div></Card>
 <Card><div className="toolbar"><h3>Daftar Nilai</h3></div><div className="table-wrap"><table><thead><tr><th>Mata Pelajaran</th><th>Semester</th><th>Komponen</th><th>Nilai</th></tr></thead><tbody>{grades.map(g=><tr key={g.id}><td>{g.subject}</td><td>{g.semester}</td><td>{g.field?.toUpperCase()}</td><td><b>{g.score}</b></td></tr>)}</tbody></table></div></Card></>}</>
}
