import { useMemo,useState } from 'react'
import { Card,ExportBar } from '../components/Common'
export default function ParentPortal({data,studentId}){
 const [selected,setSelected]=useState(studentId||data.students[0]?.id);const s=data.students.find(x=>x.id===selected)
 const grades=(data.grades||[]).filter(g=>g.studentId===selected),att=(data.attendance||[]).filter(a=>a.studentId===selected)
 const avg=grades.length?Math.round(grades.reduce((a,b)=>a+Number(b.score||0),0)/grades.length):0
 const counts=['Hadir','Sakit','Izin','Alpa','Terlambat'].map(x=>[x,att.filter(a=>a.status===x).length])
 const latest=useMemo(()=>grades.slice(-12),[grades]);const rows=grades.map(g=>[g.subject,`Semester ${g.semester}`,g.field?.toUpperCase(),g.score])
 return <><div className="page-head"><div><h1>Portal Orang Tua</h1><p>Pantau nilai dan kehadiran siswa.</p></div>{!studentId&&<select value={selected} onChange={e=>setSelected(e.target.value)}>{data.students.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}</div>{s&&<><Card className="student-profile"><div className="avatar">{s.name[0]}</div><div><h2>{s.name}</h2><p>NISN {s.nisn} · Kelas {data.settings.className}</p><small>Orang tua: {s.parent}</small></div><div className="score-ring"><b>{avg}</b><span>Rata-rata</span></div></Card><div className="grid2"><Card><h3>Ringkasan Kehadiran</h3><div className="attendance-bars">{counts.map(([x,n])=><div key={x}><span>{x}</span><div><i style={{width:`${Math.min(100,n*10)}%`}}/></div><b>{n}</b></div>)}</div></Card><Card><h3>Perkembangan Nilai</h3><div className="grade-chart">{latest.map(g=><div key={g.id} title={`${g.subject} ${g.field}: ${g.score}`}><i style={{height:`${g.score}%`}}/><small>{g.field?.toUpperCase()}</small></div>)}</div></Card></div><Card><div className="toolbar"><h3>Daftar Nilai</h3><ExportBar title={`Nilai ${s.name}`} columns={['Mata Pelajaran','Semester','Komponen','Nilai']} rows={rows}/></div><div className="table-wrap"><table><thead><tr><th>Mata Pelajaran</th><th>Semester</th><th>Komponen</th><th>Nilai</th></tr></thead><tbody>{grades.map(g=><tr key={g.id}><td>{g.subject}</td><td>{g.semester}</td><td>{g.field?.toUpperCase()}</td><td><b>{g.score}</b></td></tr>)}</tbody></table></div></Card></>}</>
}
