import { useMemo,useState } from 'react'
import * as XLSX from 'xlsx'
import { Card,Select } from '../components/Common'
import { FileSpreadsheet, Printer, Eye, BookOpen, Files } from 'lucide-react'
import { subjects } from '../data'

const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))
const dateID=d=>new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d||Date.now()))
const semesterRange=(year,semester)=>{const y=Number(String(year).slice(0,4));return semester==='1'?[`${y}-07-01`,`${y}-12-31`]:[`${y+1}-01-01`,`${y+1}-06-30`]}
const att=(data,sid,semester)=>{const [a,b]=semesterRange(data.settings.year,semester),r=(data.attendance||[]).filter(x=>x.studentId===sid&&x.date>=a&&x.date<=b);return{Sakit:r.filter(x=>x.status==='Sakit').length,Izin:r.filter(x=>x.status==='Izin').length,Alpa:r.filter(x=>x.status==='Alpa').length}}
const profileText='Pada semester ini, ananda menunjukkan capaian yang baik dalam penguatan profil lulusan. Ananda berkembang dalam keimanan dan ketakwaan, kewargaan, penalaran kritis, kreativitas, kemandirian, kolaborasi, serta komunikasi.'

function reportHtml(data,student,semester,reportDate,coverOnly=false){
 const grades=subjects.map(subject=>({subject,g:(data.reportGrades||[]).find(x=>x.studentId===student.id&&x.subject===subject&&String(x.semester)===String(semester))})).filter(x=>x.g)
 const comp=(data.reportCompleteness||{})[`${student.id}|${semester}`]||{}, absence=att(data,student.id,semester)
 const cover=`<section class="page cover"><img src="/tutwuri-handayani-clean.png" class="tut"><h1>SEKOLAH DASAR<br>( SD )</h1><img src="/logo-kabupaten-bekasi.png?v=4" class="kab"><h2>Nama Peserta Didik</h2><div class="box">${esc(student.name).toUpperCase()}</div><h2>NISN / NIS</h2><div class="box">${esc(student.nisn)} / ${esc(student.nis)}</div><h3>KEMENTERIAN PENDIDIKAN DASAR DAN MENENGAH<br>REPUBLIK INDONESIA</h3></section>`
 if(coverOnly)return cover
 const rows=grades.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.subject)}</td><td>${x.g.score}</td><td>${esc(x.g.description)}</td></tr>`).join('')||'<tr><td colspan="4">Belum ada nilai rapor tersimpan.</td></tr>'
 const extra=(comp.extracurriculars||[]).filter(x=>x.name).map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.grade)} ${esc(x.description)}</td></tr>`).join('')||'<tr><td>1</td><td></td><td></td></tr><tr><td>2</td><td></td><td></td></tr>'
 return cover+`<section class="page report"><div class="identity"><div>Nama Murid <b>: ${esc(student.name)}</b><br>NIS/NISN <b>: ${esc(student.nis)} / ${esc(student.nisn)}</b><br>Sekolah <b>: ${esc(data.settings.school)}</b><br>Alamat <b>: ${esc(student.address)}</b></div><div>Kelas <b>: Kelas ${esc(data.settings.className)}</b><br>Semester <b>: ${semester}</b><br>Tahun Ajaran <b>: ${esc(data.settings.year)}</b></div></div><hr><h1>LAPORAN HASIL BELAJAR</h1><h2>A. Sikap</h2><table><tr><th>Deskripsi Capaian Profil Lulusan</th></tr><tr><td class="desc">${esc(comp.profileDescription||profileText)}</td></tr></table><h2>B. Pengetahuan dan Keterampilan</h2><table><thead><tr><th>No</th><th>Mata Pelajaran</th><th>Nilai Akhir</th><th>Capaian Kompetensi</th></tr></thead><tbody>${rows}</tbody></table><footer>Kelas ${esc(data.settings.className)} &nbsp;|&nbsp; ${esc(student.name)} &nbsp;|&nbsp; ${esc(student.nis)} <span>Halaman : 1</span></footer></section><section class="page report"><div class="identity"><div>Nama Murid <b>: ${esc(student.name)}</b><br>NIS/NISN <b>: ${esc(student.nis)} / ${esc(student.nisn)}</b><br>Sekolah <b>: ${esc(data.settings.school)}</b></div><div>Kelas <b>: Kelas ${esc(data.settings.className)}</b><br>Semester <b>: ${semester}</b><br>Tahun Ajaran <b>: ${esc(data.settings.year)}</b></div></div><hr><table><thead><tr><th>No</th><th>Ekstrakurikuler</th><th>Keterangan</th></tr></thead><tbody>${extra}</tbody></table><div class="lower"><table><tr><th colspan="2">Ketidakhadiran</th></tr><tr><td>Sakit</td><td>: ${absence.Sakit} hari</td></tr><tr><td>Izin</td><td>: ${absence.Izin} hari</td></tr><tr><td>Tanpa Keterangan</td><td>: ${absence.Alpa} hari</td></tr></table><table><tr><th>Catatan Wali Kelas</th></tr><tr><td class="note">${esc(comp.teacherNote||'')}</td></tr></table></div><table><tr><th>Tanggapan Orang Tua/Wali Murid</th></tr><tr><td class="parent-note">${esc(comp.parentResponse||'')}</td></tr></table><div class="sign"><div>Orang Tua Murid<br><br><br><b>......................................</b></div><div>Kepala Sekolah<br><br><br><b>${esc(data.settings.principal||'Kepala Sekolah')}</b><br>NIP. ${esc(data.settings.principalNip||'-')}</div><div>Bekasi, ${dateID(reportDate)}<br>Wali Kelas<br><br><br><b>${esc(data.settings.teacher)}</b><br>NIP. ${esc(data.settings.teacherNip)}</div></div><footer>Kelas ${esc(data.settings.className)} &nbsp;|&nbsp; ${esc(student.name)} &nbsp;|&nbsp; ${esc(student.nis)} <span>Halaman : 2</span></footer></section>`
}
function openPrint(html,title){const w=window.open('','_blank');if(!w)return alert('Popup diblokir browser. Izinkan popup untuk mencetak.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial;color:#111}.page{width:210mm;height:297mm;page-break-after:always;position:relative;padding:12mm 10mm;background:white}.cover{text-align:center;padding-top:17mm}.tut{width:46mm;height:46mm;object-fit:contain}.kab{display:block;width:32mm;height:36mm;object-fit:contain;margin:6mm auto 10mm}.cover h1{font-size:27px;line-height:1.5}.cover h2{font-size:19px;margin:9mm 0 2mm}.cover .box{border:1px solid #333;width:70%;margin:auto;padding:3mm;font-size:19px;font-weight:bold}.cover h3{margin-top:18mm;font-size:20px;line-height:1.55}.identity{display:flex;justify-content:space-between;line-height:1.55;font-size:12px}.report h1{text-align:center;font-size:20px}.report h2{font-size:15px}table{border-collapse:collapse;width:100%;margin:4mm 0}th,td{border:1px solid #333;padding:2mm;font-size:10px}th{background:#f5f6f8}.desc{height:68mm;vertical-align:top;font-size:11px;line-height:1.4}.lower{display:grid;grid-template-columns:35% 65%;gap:5mm}.note{height:30mm}.parent-note{height:30mm}.sign{display:grid;grid-template-columns:1fr 1fr 1fr;text-align:center;margin-top:5mm;font-size:11px;line-height:1.3}footer{position:absolute;left:10mm;right:10mm;bottom:7mm;border-top:1px solid #333;padding-top:2mm;font-size:9px;font-weight:bold}footer span{float:right}@media print{body{-webkit-print-color-adjust:exact}.page{break-after:page}}</style></head><body>${html}</body></html>`);w.document.close();setTimeout(()=>w.print(),500)}

export default function ReportPrint({data}){
 const [studentId,setStudentId]=useState(data.students[0]?.id||''),[semester,setSemester]=useState(data.settings.semester||'1'),[reportDate,setReportDate]=useState(new Date().toISOString().slice(0,10))
 const student=data.students.find(x=>x.id===studentId)
 const gradeMap=useMemo(()=>Object.fromEntries((data.reportGrades||[]).filter(x=>String(x.semester)===String(semester)).map(x=>[`${x.studentId}|${x.subject}`,x.score])),[data.reportGrades,semester])
 const print=(kind)=>{if(kind==='all')openPrint(data.students.map(s=>reportHtml(data,s,semester,reportDate)).join(''),`Rapor Kelas ${data.settings.className}`);else openPrint(reportHtml(data,student,semester,reportDate,kind==='cover'),kind==='cover'?'Cover Rapor':`Rapor ${student.name}`)}
 const exportLeger=()=>{const headers=['No','NIS','NISN','Nama Siswa',...subjects,'Total','Rata-rata','Peringkat','Sakit','Izin','Alpa'];const base=data.students.map((s,i)=>{const vals=subjects.map(sub=>Number(gradeMap[`${s.id}|${sub}`]||0)),total=vals.reduce((a,b)=>a+b,0),avg=vals.filter(Boolean).length?total/vals.filter(Boolean).length:0,a=att(data,s.id,semester);return{student:s,total,avg,row:[i+1,s.nis,s.nisn,s.name,...vals.map(v=>v||''),total,Number(avg.toFixed(2)),0,a.Sakit,a.Izin,a.Alpa]}});[...base].sort((a,b)=>b.avg-a.avg).forEach((x,i)=>x.rank=i+1);base.forEach(x=>x.row[4+subjects.length]=x.rank);const ws=XLSX.utils.aoa_to_sheet([[`LEGER NILAI KELAS ${data.settings.className} SEMESTER ${semester}`],[data.settings.school,`Tahun Pelajaran ${data.settings.year}`],[],headers,...base.map(x=>x.row)]);ws['!cols']=[{wch:5},{wch:14},{wch:14},{wch:28},...subjects.map(()=>({wch:16})),{wch:10},{wch:12},{wch:10},{wch:8},{wch:8},{wch:8}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Leger');XLSX.writeFile(wb,`LEGER-KELAS-${data.settings.className}-SEMESTER-${semester}.xlsx`)}
 return <><div className="page-head"><div><h1>Cetak Rapor & Leger</h1><p>Format rapor mengikuti contoh PDF, dengan absensi semester otomatis.</p></div></div><Card><div className="erapor-filters"><Select label="Semester" value={semester} onChange={e=>setSemester(e.target.value)}><option value="1">Semester 1</option><option value="2">Semester 2</option></Select><Select label="Siswa" value={studentId} onChange={e=>setStudentId(e.target.value)}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><label>Tanggal Pembagian Rapor<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label></div><div className="print-action-grid"><button onClick={()=>print('cover')}><BookOpen/>Cetak Cover Rapor</button><button className="primary" onClick={()=>print('single')}><Printer/>Cetak Rapor Siswa</button><button onClick={()=>print('all')}><Files/>Cetak Seluruh Kelas</button><button onClick={()=>print('single')}><Eye/>Preview Rapor</button><button onClick={exportLeger}><FileSpreadsheet/>Export Leger Excel</button></div></Card></>
}
