import { useRef,useState } from 'react'
import { Download,Upload,Save,RotateCcw } from 'lucide-react'
import { Card,Field,Select } from '../components/Common'
import { downloadBlob } from '../utils/storage'
export default function Settings({data,setData}){
 const [form,setForm]=useState(data.settings),file=useRef(); const save=e=>{e.preventDefault();setData(d=>({...d,settings:form}));alert('Pengaturan tersimpan.')}
 const backup=()=>downloadBlob(JSON.stringify(data,null,2),`backup-kelas-5b-${new Date().toISOString().slice(0,10)}.json`,'application/json')
 const restore=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.students||!d.settings)throw Error();setData(d);alert('Backup berhasil dipulihkan.')}catch{alert('File backup tidak valid.')}};r.readAsText(f)}
 return <><div className="page-head"><div><h1>Pengaturan</h1><p>Identitas sekolah, semester, akun guru, tema, backup dan restore.</p></div></div><div className="grid2"><Card><h3>Identitas Sekolah</h3><form onSubmit={save}><Field label="Nama Sekolah" value={form.school||''} onChange={e=>setForm({...form,school:e.target.value})}/><div className="form-grid"><Field label="Status Sekolah" value={form.status||''} onChange={e=>setForm({...form,status:e.target.value})}/><Field label="Kelas" value={form.className||''} onChange={e=>setForm({...form,className:e.target.value})}/></div><Field label="Alamat" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/><div className="form-grid"><Field label="Desa/Kelurahan" value={form.village||''} onChange={e=>setForm({...form,village:e.target.value})}/><Field label="Kecamatan" value={form.district||''} onChange={e=>setForm({...form,district:e.target.value})}/><Field label="Kabupaten/Kota" value={form.city||''} onChange={e=>setForm({...form,city:e.target.value})}/><Field label="Provinsi" value={form.province||''} onChange={e=>setForm({...form,province:e.target.value})}/><Field label="Tahun Pelajaran" value={form.year||''} onChange={e=>setForm({...form,year:e.target.value})}/><Select label="Semester Aktif" value={form.semester||'1'} onChange={e=>setForm({...form,semester:e.target.value})}><option value="1">1 (Satu)</option><option value="2">2 (Dua)</option></Select></div><Field label="Nama Wali Kelas" value={form.teacher||''} onChange={e=>setForm({...form,teacher:e.target.value})}/><Field label="NIP Wali Kelas" value={form.teacherNip||''} onChange={e=>setForm({...form,teacherNip:e.target.value})}/><Field label="Warna Utama" type="color" value={form.accent||'#155e75'} onChange={e=>setForm({...form,accent:e.target.value})}/><button className="primary wide"><Save/>Simpan Pengaturan</button></form></Card><Card><h3>Akun Guru</h3><Field label="Username" value={form.teacherUsername||''} onChange={e=>setForm({...form,teacherUsername:e.target.value})}/><Field label="Kata Sandi" type="password" value={form.teacherPassword||''} onChange={e=>setForm({...form,teacherPassword:e.target.value})}/><hr/><h3>Backup & Restore</h3><p className="muted">Simpan seluruh data ke JSON atau pulihkan dari file backup.</p><div className="backup-actions"><button onClick={backup}><Download/>Unduh Backup</button><button onClick={()=>file.current.click()}><Upload/>Restore Backup</button><input ref={file} hidden type="file" accept=".json" onChange={restore}/><button className="danger" onClick={()=>{if(confirm('Kembalikan semua data ke kondisi awal?')){localStorage.removeItem('ak5b_data_v2');location.reload()}}}><RotateCcw/>Reset Data Awal</button></div></Card></div></>
}
